
library
```{r}
library(dplyr)
library(tidyverse)
```



## ecoli
```{r}


# Example data
df <- readr::read_csv("ecoli_unaligned.csv")
names(df)

# Extract group (before first underscore, e.g., "Ecoli_HS" or "Ecoli_Std")
df <- df %>%
  mutate(group = sub("(_[A-H][0-9]{2}-contigs)$", "", sample_id))

# Calculate group statistics
summary_df <- df %>%
  group_by(group) %>%
  summarise(
    mean_pct = mean(unaligned_pct),
    se = sd(unaligned_pct) / sqrt(n())
  )

# Plot mean ± SE
ggplot(summary_df, aes(x = group, y = mean_pct, fill = group)) +
  geom_col(width = 0.7) +
  geom_errorbar(aes(ymin = mean_pct - se, ymax = mean_pct + se),
                width = 0.2) +
  theme_minimal(base_size = 14) +
  theme(legend.position = "none") +
  labs(
    title = "Percent of Unaligned Assembled Reads",
    x = "",
    y = "Mean Unaligned Percent ± SE"
  )

```


## salmonella
```{r}


# Example data
df <- readr::read_csv("salmonella_unaligned.csv")
names(df)

# Extract group (before first underscore, e.g., "Ecoli_HS" or "Ecoli_Std")
df <- df %>%
  mutate(group = sub("(_[A-H][0-9]{2}-contigs)$", "", sample_id))

# Calculate group statistics
summary_df <- df %>%
  group_by(group) %>%
  summarise(
    mean_pct = mean(unaligned_pct),
    se = sd(unaligned_pct) / sqrt(n())
  )

# Plot mean ± SE
ggplot(summary_df, aes(x = group, y = mean_pct, fill = group)) +
  geom_col(width = 0.7) +
  geom_errorbar(aes(ymin = mean_pct - se, ymax = mean_pct + se),
                width = 0.2) +
  theme_minimal(base_size = 14) +
  theme(legend.position = "none") +
  labs(
    title = "Percent of Unaligned Assembled Reads",
    x = "",
    y = "Mean Unaligned Percent ± SE"
  )

```

